name: Security & Dependencies

on:
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Frontend security audit
    - name: Frontend - Install dependencies
      run: cd frontend && npm ci

    - name: Frontend - Security audit
      run: cd frontend && npm audit --audit-level=moderate

    # Backend security audit
    - name: Backend - Install dependencies
      run: cd backend && npm ci

    - name: Backend - Security audit
      run: cd backend && npm audit --audit-level=moderate

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: moderate